# Generated by Django 4.1.3 on 2023-03-01 09:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_product_image_alter_orderitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="image", max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="image", max_length=255, verbose_name="image"
            ),
        ),
    ]
