# Generated by Django 4.1.3 on 2023-03-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_alter_orderitem_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
